---
title: "Project G: Collaborating on Projects"
author: "Benjamin Leslie"
date: March 14, 2023
output: html_notebook
---


An analysis of variance was conducted to compare HSB2 science performances for three socioeconomic groups. The data set was found to satisfy the criteria for conducting a valid ANOVA as the groups were independent, the units within groups were independent, the data is normally distributed, and the distribution is not skewed. Using the ANOVA, we can say with a 95% level of confidence that there is not a statistically significant difference between two or more of the groups. T tests were then used to compare the mean science scores for each SES level. These tests found high SES students obtained higher scores than middle or low SES students. The results also found that middle SES students obtained higher scores than low SES students. It is important to note that the 95% confidence intervals for high-middle and middle-low had upper bounds between -1 and 0. This suggests that the high-low relationship had much stronger evidence of a difference between groups.

Using bootstrapping, a 95% confidence interval for the true population mean science score was found to be `r round(boot_int[1],2)` < $mu$ < `r round(boot_int[2],2)`. A Tukey pairwise estimate was conducted and found that only the high-low relationship yielded a statistically significant p value, p > 0.05. This relationship was also the only one to yield a confidence interval that did not contain zero. This supports that the high-low SES mean score difference does not equal zero with 95 percent confidence.

In total, these findings suggest that there is mixed evidence to support a difference in science scores between socioeconomic status levels. It is worth noting that the relationship between low SES and high SES students' scores yielded the most consistent evidence to support a difference in the mean score of the two groups.




